export const phoneNumber = '+55 (84) 99612-2402'
export const phoneNumber2 = '+55 (84) 99612-2402'
export const wpLink = 'https://wa.me/5584996122402'
export const gitLink = 'https://github.com/vinic-i'
export const instaLink = 'https://www.instagram.com/vinic.i/?hl=pt-br'
export const LinkedIn = ''
export const locationLink = ''
export const contactEmail = 'mixount@gmail.com'
export const infoEmail = 'info@mixount.com'
export const address = 'Av dos Xavantes, 347-b'
export const country = 'Brasil'
export const city = 'Natal, RN'